name: quiz

on:
  push:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint
      - run: npm run test

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @railway/cli
      - run: railway up --service=cicdnest
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - run: echo "레일웨이 배포 완료"
  arombake:
    runs-on: ubuntu-latest
    steps:
      - name: 'dubai mochi'
        run: echo "두바이 모찌빵"

      - name: 'sweet potato'
        run: echo "고구마 모찌빵 왜 사먹음?"

      - name: 'eggtart'
        run: echo "에그타르트 모찌빵"
